#!/bin/bash

apt update -y

# Установка необходимых пакетов
sudo apt install -y nano mysql-server-8.0
echo "Mysql 8.0 установленна"

# Добавление в автозагрузку
systemctl enable mysql
systemctl restart mysql

# Изменение bind-address в MySQL
sed -i 's/bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf
echo "server-id              = 2" >> /etc/mysql/mysql.conf.d/mysqld.cnf
service mysql restart

# Настройка MySQL
mysql -e "CREATE USER 'root'@'%' IDENTIFIED BY 'adm';"
mysql -uroot -padm -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
mysql -uroot -padm -e "STOP SLAVE;"
mysql -uroot -padm -e "set global sql_slave_skip_counter=1;"
# Запрашиваем у пользователя параметры
read -p "Enter MASTER_HOST: " master_host
read -p "Enter MASTER_USER: " master_user
read -p "Enter MASTER_PASSWORD: " master_password
read -p "Enter MASTER_LOG_FILE: " master_log_file
read -p "Enter MASTER_LOG_POS: " master_log_pos

# Формируем SQL-запрос на основе введенных данных
sql="CHANGE MASTER TO MASTER_HOST='$master_host', MASTER_USER='$master_user', MASTER_PASSWORD='$master_password', MASTER_LOG_FILE='$master_log_file', MASTER_LOG_POS=$master_log_pos, GET_MASTER_PUBLIC_KEY = 1;"

echo "Executing: $sql"
mysql -u root -padm -e "$sql"

mysql -uroot -padm -e "START SLAVE;"

mysql -uroot -padm -e "show slave status\G;"
